### ISSUE TITLE
Android - Java Ilegal exception

### ISSUE THREAD

**Issue by juanagu** [Pushwoosh/pushwoosh-xamarin#10]
When the app start it throws the following exception:

Method 'void android.support.v4.content.ContextCompat.<init>()' is inaccessible to class 'com.google.android.gms.iid.zzd' (declaration of 'com.google.android.gms.iid.zzd' appears in /data/app/package-1/base.apk)

packages:

<package id="Xamarin.Android.Support.Animated.Vector.Drawable" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Annotations" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Compat" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Core.UI" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Core.Utils" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Design" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Fragment" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Media.Compat" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Transition" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v4" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.AppCompat" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.CardView" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.MediaRouter" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.Palette" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.RecyclerView" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Vector.Drawable" version="25.3.1" targetFramework="monoandroid71" />
.
.
.
<package id="Xamarin.GooglePlayServices.Base" version="29.0.0.2" targetFramework="monoandroid71" />
  <package id="Xamarin.GooglePlayServices.Basement" version="29.0.0.2" targetFramework="monoandroid71" />
  <package id="Xamarin.GooglePlayServices.Gcm" version="29.0.0.2" targetFramework="monoandroid71" />
  <package id="Xamarin.GooglePlayServices.Measurement" version="29.0.0.2" targetFramework="monoandroid71" />
.
.
.
<package id="Xamarin.Forms" version="2.3.4.247" targetFramework="monoandroid71" />
.
.
.
<package id="Pushwoosh.Xamarin.Droid" version="4.12.2" targetFramework="monoandroid71" />
.
.
.

**Comment by juanagu** [comment]
Same error: 
https://forums.xamarin.com/discussion/98098/getting-an-error-java-lang-illegalaccesserror-while-retrieving-token-from-gcm-services

**Comment by juanagu** [comment]
I run the sample and it does not work.

**Comment by DimanAM** [comment]
This error indicates inconsistent Android Support v4 and Google Play Services library versions. What versions of Xamarin.Android.Support.v4 and Xamarin.GooglePlayServices.* packages do you use? Try updating them to the latest version.
