### ISSUE TITLE
How detect when user open notification? (Android and iOS)

### ISSUE THREAD

**Issue by juanagu** [Pushwoosh/pushwoosh-xamarin#11]

**Comment by wfhm** [comment]
Hi,

For Android you can use `doOnMessageReceive` method:

https://github.com/Pushwoosh/pushwoosh-xamarin/blob/master/Samples/Droid/PushwooshSample/MainActivity.cs#L146

For iOS add the following method to your AppDelegate class and handle a push open event in it:

```
[Export("onPushAccepted:withNotification:onStart:")]
public void OnPushAccepted(PushNotificationManager pushManager, NSDictionary pushNotification, bool onStart) {
}
```
