### ISSUE TITLE
PushNotificationDelegate is missing in Xamarin.iOS Assembly

### ISSUE THREAD

**Issue by martijn00** [Pushwoosh/pushwoosh-xamarin#12]
It appears either the wrong version of Pushwoosh for iOS is up on Nuget or the version is not updated to 5.3.1. Can you guys check this?

**Comment by wfhm** [comment]
Hi,

Checking this. Meanwhile you can use Pushwoosh module from this repo.

**Comment by fectum89** [comment]
Fixed. Please update Pushwoosh package.
