### ISSUE TITLE
NuGET / repo version mismatch

### ISSUE THREAD

**Issue by ndastur** [Pushwoosh/pushwoosh-xamarin#13]
Hi. I went across to the NuGET package page (https://www.nuget.org/packages/Pushwoosh.Xamarin.iOS/5.4.0) and it seems there is a version ahead of the one in this repo. Also the .nuspec file still specifies 5.3.1 but the commit says 5.3.5. Is it possible to tidy up the versioning. Just we can be clear on the API. Thank you

**Comment by wfhm** [comment]
Hey @ndastur ,

Thanks for pointing it out! Will be fixed shortly.

**Comment by ndastur** [comment]
No problem. About to migrate from another provider, hence looking and picked up. Are you also able to look at the samples for .Net as there seem to be some differences between website docs and samples here. Thanks

**Comment by wfhm** [comment]
@ndastur fixed with the latest release.
