### ISSUE TITLE
Android - Crash with RegisterForPushNotifications

### ISSUE THREAD

**Issue by AeonDave** [Pushwoosh/pushwoosh-xamarin#14]
Hello,
i installed the NuGet Package v 5.4.1 (Pushwoosh.Xamarin.Droid) and i followed the guide from docs but after 
`PushNotificationsManager.Instance.RegisterForPushNotifications();`
i receive from the console this message:
`Pushwoosh] Exception occurred
[Pushwoosh] java.lang.IllegalArgumentException: Please set the mAppId constant and recompile the app.
[Pushwoosh] 	at com.pushwoosh.internal.platform.utils.GeneralUtils.checkNotNullOrEmpty(Unknown Source)
[Pushwoosh] 	at com.pushwoosh.gcm.b.a.a$a.a(Unknown Source)
[Pushwoosh] 	at com.pushwoosh.gcm.b.a.a.checkDevice(Unknown Source)
[Pushwoosh] 	at com.pushwoosh.notification.e.a(Unknown Source)
[Pushwoosh] 	at com.pushwoosh.Pushwoosh.registerForPushNotifications(Unknown Source)
....`

Firebase is correctly configured because we use crash report inside it and also our app in the PW application manager site.

Is a bug or a misconfig?
there isn't anywhere a constant which i can set called mAppId.

thank you

**Comment by wfhm** [comment]
Hi,

It looks like Pushwoosh Application ID is not set in your app. Please make sure you have it added to your AndroidManifest.xml:

```
<meta-data android:name="com.pushwoosh.appid" android:value="XXXXX-XXXXX" /> //XXXXX-XXXXX is an application ID you can find in Pushwoosh Control Panel
```

**Comment by PrafullaAlgorythma** [comment]
Even after setting <meta-data android:name="com.pushwoosh.appid" android:value="XXXXX-XXXXX" /> getting same error "Please set the mAppId constant and recompile the app.". Not sure what else it wants.
