### ISSUE TITLE
Custom NotificationServiceExtension due to duplicate meta-data

### ISSUE THREAD

**Issue by vixez** [Pushwoosh/pushwoosh-xamarin#16]
Hello,

I found (and worked around) an issue with the library, which prevents a custom NotificationServiceExtension from working.

The file Library/Pushwoosh.Droid/PushwooshNotificationServiceExtension.cs contains the following line
`[assembly: MetaData("com.pushwoosh.notification_service_extension",Value = "com.pushwoosh.plugin.PushwooshNotificationServiceExtension")]`

This will cause a meta-data tag to be added to AndroidManifest.xml
`<meta-data android:name="com.pushwoosh.notification_service_extension" android:value="com.pushwoosh.plugin.PushwooshNotificationServiceExtension"/>`

As the [instructions](https://www.pushwoosh.com/docs/migration) for a custom NotificationServiceExtension tell you to also use the `assembly: MetaData` code for your custom extension. This will add a second meta-data tag to AndroidManifest.xml. But it appears this meta-data tag is ignored, only the first one in the Pushwoosh library is used.
Therefore the custom NotificationServiceExtension will never work.

If you comment out the assembly: MetaData line in the library, rebuild the library and use it in your project the custom NotificationServiceExtension will work.

I have not tested what the implications are of skipping the NotificationServiceExtension of the library itself, but this fixes the custom NotificationServiceExtension.

Just thought I'd post this here in case someone else bumps into this issue.

**Comment by wfhm** [comment]
Hi @vixez ,

Thanks for reporting this one, will check it and see if we can do something with it. I will post a result of our research shortly.

**Comment by wfhm** [comment]
@vixez The issue is only reproducible if you specify a different name for your Notification Service Extension class - it should always be PushwooshNotificationServiceExtension, otherwise it will indeed be ignored. Could you please confirm that you were using a different one, or, if you had specified exactly this name, provide us with a reproducer project?

Please also note that I have just tested [Xamarin.Droid sample app](https://github.com/Pushwoosh/pushwoosh-xamarin/tree/master/Samples/Droid) (which has such an extension) and it has worked just fine.

**Comment by wfhm** [comment]
@vixez any news on this one? Also, do you use Xamarin.Forms or just bindings for Android?

**Comment by vixez** [comment]
Hello,
Sorry, been very busy. I will check next week.
I'm using Xamarin bindings, not Forms.

**Comment by vixez** [comment]
Hello,
Sorry, been very busy. I will check next week.
I'm using Xamarin bindings, not Forms.

In the manifest it is declared as so:

`<meta-data android:name="com.pushwoosh.notification_service_extension" android:value="com.package.name.PushwooshNotificationServiceExtension" />`

The class:
```
[assembly: MetaData("com.pushwoosh.notification_service_extension", Value = "com.package.name.PushwooshNotificationServiceExtension")]
namespace My_Namespace {

    [Register("com/package/name/PushwooshNotificationServiceExtension")]
    public class PushwooshNotificationServiceExtension : NotificationServiceExtension {

        protected override void StartActivityForPushMessage(PushMessage message) {
           // My app logic
    }

}
```

**Comment by wfhm** [comment]
@vixez 

You should link [Pushwoosh.Xamarin.Droid bindings](https://www.nuget.org/packages/Pushwoosh.Xamarin.Droid) to your Android project, and [Pushwoosh.Xamarin.iOS bindings](https://www.nuget.org/packages/Pushwoosh.Xamarin.iOS) then. This should fix your issue.

**Comment by vixez** [comment]
@wfhm 

That is what I did before. The iOS project is still using the NuGet package.
I had to remove the Android package and import it manually with the above changes to make it work.

**Comment by wfhm** [comment]
@vixez please note that the code that causes your issue is located in 

https://www.nuget.org/packages/Pushwoosh/ package and not in https://www.nuget.org/packages/Pushwoosh.Xamarin.Droid/ or https://www.nuget.org/packages/Pushwoosh.Xamarin.iOS/ .

**Comment by wfhm** [comment]
@vixez any news?
