### ISSUE TITLE
Problem trying to upload to App Store.

### ISSUE THREAD

**Issue by Kelderth** [Pushwoosh/pushwoosh-xamarin#29]
Good night, I was trying to upload my App developed with Xamarin Forms to the App Store and they are rejecting my app, doing some analysis I noticed that Pushwoosh.iOS.Bindings is still using UIKit.UIWebView.

So I would like to know what are you doing about this situations.

The current NuGet Version is Pushwoosh 5.23.0 .0 and Xamarin Forms 4.6.0.726

This is the console output:
 
MTOUCH : warning MT1502: One or more reference(s) to type 'UIKit.UIWebView' already exists inside 'Pushwoosh.iOS.Bindings, Version=5.23.0.0, Culture=neutral, PublicKeyToken=null' before linking

**Comment by wfhm** [comment]
Hi @Kelderth,

Checking it

**Comment by wfhm** [comment]
Fixed in 5.23.1

**Comment by Kelderth** [comment]
Thank you!
