### ISSUE TITLE
Pushwoosh Xamarin dependencies

### ISSUE THREAD

**Issue by dhiraj-shetty** [Pushwoosh/pushwoosh-xamarin#30]
Dear Pushwoosh Xamarin SDK Team,

Please confirm whether the latest released version on Nuget i.e. 5.23.1 is dependent on older versions of Xamarin libraries. We will get back with precise errors thrown during compilation (if required). 

To summarize we get version conflicts with existing installed (updated) Nuget packages. We are working around this problem by resolving the dependency chain. However please note that the size of our Android App apk seems to have increased from around 30MB to 65MB when we added support for Pushwoosh based push and resolved all the dependencies.

However since we do not see others reporting such problems on the internet, we are wondering whether there could be something wrong or missing in our steps. Looking forward to your guidance.

Regards,
Dhiraj.

**Comment by wfhm** [comment]
Hi! Checking it

**Comment by wfhm** [comment]
@dhiraj-shetty here are the dependencies used by our Xamarin lib:

https://github.com/Pushwoosh/pushwoosh-xamarin/blob/master/Core/Library/Pushwoosh.Droid/packages.config

Could you please let us know more about the dependencies conflicts you got?

**Comment by dhiraj-shetty** [comment]
Thank you for your prompty reply. First we get an error saying "Cannot resolve reference: `Xamarin.Android.Arch.Work.Runtime`, referenced by `Pushwoosh.Droid.Bindings`. Please add a NuGet package or assembly reference for `Xamarin.Android.Arch.Work.Runtime`, or remove the reference to `Pushwoosh.Droid.Bindings`


To resolve the above error if we install Xamarin.Android.Arch.Work.Runtime 1.0.0.3 (the latest available version):

Version conflict detected for Xamarin.Android.Support.Compat. Install/reference Xamarin.Android.Support.Compat 28.0.0.3 directly to project USR_Practice.Android to resolve this issue. 

 USR_Practice.Android -> Xamarin.Android.Arch.Work.Runtime 1.0.0.3 -> Xamarin.Android.Arch.Persistence.Room.Runtime 1.1.1.3 -> Xamarin.Android.Support.Core.Utils 28.0.0.3 -> Xamarin.Android.Support.Compat (= 28.0.0.3) 

 USR_Practice.Android -> Pushwoosh 5.23.1 -> Pushwoosh.Xamarin.Droid 5.22.6 -> Xamarin.Android.Support.v4 26.0.2 -> Xamarin.Android.Support.Compat (= 26.0.2).

Please note that we are relatively new to Xamarin and are in process of developing our first App. Please feel free to correct any mistake we may be doing.

**Comment by wfhm** [comment]
@dhiraj-shetty 
`Pushwoosh.Droid.Bindings` does have this dependency: 
https://github.com/Pushwoosh/pushwoosh-xamarin/blob/master/Core/Bindings/Android/packages.config#L16

I have just tried to reproduce the issue, and all dependencies were correctly added with this sample app:
https://github.com/Pushwoosh/pushwoosh-xamarin/tree/master/Samples/Droid

Could you please share a reproducer project with us and describe the exact steps to reproduce the issue?

**Comment by dhiraj-shetty** [comment]
Dear Vitaly,

We have given you collaborator access to our repository.

Once you have downloaded the code and try to build it, you are expected to get the following compilation error:
"Cannot resolve reference: Xamarin.Android.Arch.Work.Runtime, referenced by Pushwoosh.Droid.Bindings. Please add a NuGet package or assembly reference for Xamarin.Android.Arch.Work.Runtime, or remove the reference to Pushwoosh.Droid.Bindings

Please confirm on how we can resolve this error, without adding unnecessary nuget packages to the Android Project.

Regards,
Dhiraj.

**Comment by wfhm** [comment]
@dhiraj-shetty got it reproduced. This happens because Pushwoosh package is still not migrated to AndroidX, and when Android Support dependencies are added, they are not resolved correctly. The only way to fix it right now is as described here:
https://docs.microsoft.com/en-gb/xamarin/essentials/troubleshooting
After the package is migrated to AndroidX, this conflict will be resolved automatically.

**Comment by dhiraj-shetty** [comment]
Dear Vitaly,

Can you please give us some date when we will migrate to AndroidX. We are facing uninstall of our App due to APK size bloating. If there are no plans, please be explicit so that we can consider other options.

Regards,
Dhiraj.

**Comment by wfhm** [comment]
@dhiraj-shetty we expect to start working on the update mid-September. I will provide more precise ETA when there is any.

**Comment by dhiraj-shetty** [comment]
Dear Vitaly,

It looks like the wait will never end. Can you please help us out here. 

What can be done to expedite the migration?

Regards,
Dhiraj.
