### ISSUE TITLE
Getting error after Upgrading Nuget Library to v5.23.1

### ISSUE THREAD

**Issue by nsidhu-pbl** [Pushwoosh/pushwoosh-xamarin#31]
I recently upgraded nuget packages in my app to latest stable version , after the update my application is launching and is throwing exception.

I am using Pushwoosh v5.23.1 and Pushwoosh.Xamarin.Droid v5.22.6

```
Java.Lang.RuntimeException: 'Unable to get provider com.pushwoosh.PushwooshSharedDataProvider: java.lang.ClassNotFoundException: Didn't find class "com.pushwoosh.PushwooshSharedDataProvider" on path: DexPathList[[zip file "/data/app/com.myapp.Utility-T73MmYblItshh-eJ47RSYw==/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp.Utility-T73MmYblItshh-eJ47RSYw==/lib/arm64, /data/app/com.myapp.Utility-T73MmYblItshh-eJ47RSYw==/base.apk!/lib/arm64-v8a, /system/lib64]]'
```

**Comment by wfhm** [comment]
Hi @nsidhu-pbl,

Could you please specify whether you develop your app with Forms or with native bindings? It looks like Pushwoosh dependency was not added correctly. Also, what is the reason for using both Pushwoosh library (made for Forms projects) and Pushwoosh.Droid bindings?
