### ISSUE TITLE
Empty project is crashing on Android 12 with Pushwoosh.Firebase.Xamarin.Droid package is added

### ISSUE THREAD

**Issue by nicolast91** [Pushwoosh/pushwoosh-xamarin#35]
I'm having trouble migrating my Android app to API 31. It keeps crashing on Android 12 devices because of the _Pushwoosh.Firebase.Xamarin.Droid_ package.

So I created an empty Android project and I added only _Pushwoosh.Firebase.Xamarin.Droid_ to the project. When running the project on a device with API >= 31, it crashed.

The exception message is as follow:

Java.Lang.IllegalArgumentException: com.nicolastremblay.test: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/6454899/197834872-4ebb4f66-6044-44c5-b8ed-ec067a9c209b.png">

Any chance you will update the package to support API 31?

Thank you,

**Comment by wfhm** [comment]
Hi @nicolast91 , 

Checking it.

**Comment by michaelstonis** [comment]
Install the [Xamarin.AndroidX.work.runtime](https://www.nuget.org/packages/Xamarin.AndroidX.Work.Runtime/) NuGet package version 2.7.0 (or later depending on your app configurations).

reference: https://stackoverflow.com/a/70157415/165093
