### ISSUE TITLE
App Removal due to SDK

### ISSUE THREAD

**Issue by Bejasc** [Pushwoosh/pushwoosh-xamarin#37]
Hi,

Earlier this week I was contacted by Google Play - informing us that our app is non compliant with the Google Play Developer Policies.

> During review, we found that your app doesn’t comply with the[ User Data](https://support.google.com/googleplay/android-developer/answer/9888076?hl=en&ref_topic=9877467) and[ Mobile Unwanted Software](https://support.google.com/googleplay/android-developer/answer/9970222?hl=en&ref_topic=9969691) policies. We don’t allow apps that are potentially harmful to the user experience. You can read through the User Data and Mobile Unwanted Software policy pages for more details and examples of common violations.
> Your app is using the Pushwoosh SDK/Library which collects Android ID and Location. Persistent device identifiers may not be linked to other personal and sensitive user data or resettable device identifiers.

We are running the most up-to-date package available via Nuget, 6.0.6

Google have advised us that the issue must be resolved within **7 days of the notice being received - or that our app may be removed from the play store.** 

I notice https://github.com/Pushwoosh/pushwoosh-android-sdk/issues/181 mentions some work towards the issue - but we are not using the Pushwoosh Android SDK - only the Pushwoosh Xamarin SDK. 

Could you please urgently address this.

**Comment by JessieCowie23** [comment]
+1 to this

**Comment by wfhm** [comment]
@Bejasc @JessieCowie23 We are already on it, the updated version will be available shortly (today or tomorrow at latest).

**Comment by wfhm** [comment]
@Bejasc @JessieCowie23 fixed with the latest release. Please let us know should there be any issues with Play Store reviews.
