### ISSUE TITLE
Plans to support MAUI

### ISSUE THREAD

**Issue by Danielku15** [Pushwoosh/pushwoosh-xamarin#38]
What are your plans to support a .net MAUI wrapper just like for Xamarin? As far I can see should be fairly simple as already the Xamarin wrapper does not really add anything special on top beside the auto generated bindings. 

https://learn.microsoft.com/en-us/events/dotnetconf-focus-on-maui/binding-native-libraries-for-dotnet-maui
https://github.com/dotnet/maui/discussions/1340#discussioncomment-3428075
https://www.dynamsoft.com/codepool/dotnet-android-ios-nuget-package.html

**Comment by Danielku15** [comment]
@wfhm Any feedback on this topic? I saw you added some number label (internal tracking number)? I'm asking because we soon plan to start development and it would be a must to have such a wrapper. We would like to avoid developing it ourselves.

**Comment by Techsorcist** [comment]
@Danielku15, sorry for the delay in replying — wfhm on vacation right now.

We did some internal research and the team decided not to add this framework to the roadmap for now.

If you are interested in a Pushwoosh private (custom) plan, please email us at help@pushwoosh.com, and we will forward your request to the sales team. Perhaps, after their consideration, the decision can be revised in favor of supporting MAUI in the near future.

**Comment by Danielku15** [comment]
@Techsorcist We are currently in the progress to finalize our enterprise plan contract with Pushwoosh and MAUI would be a crucial requirement for us. In our evaluation phase we still used Xamarin but our apps are gradually moving to MAUI and the essential app was already migrated (without Pushwoosh integrated at this point but planned). I will reach out to you via E-mail.

**Comment by wfhm** [comment]
@Danielku15 just a quick update here. We started working on .NET MAUI support, and rough ETA is second half of April 2023 for Firebase Android and iOS. Huawei Android, Geozones, Inbox modules will be added shortly after.

**Comment by wfhm** [comment]
@Danielku15 we've rolled out the first release of our MAUI-compatible package, it is available in Nuget now under Pushwoosh.DotNet name.
Source code can be found here - https://github.com/Pushwoosh/pushwoosh-dotnet
