### ISSUE TITLE
problems trying to compile

### ISSUE THREAD

**Issue by iccunha** [Pushwoosh/pushwoosh-xamarin#4]
compiler is with the following error:
`Unhandled Exception:

problem, resolved

**Comment by DimanAM** [comment]
This issue does not seems to be related with Pushwoosh SDK anyhow.
You probably have inconsistant AndoidManifest.xml and MainActivity package location. If you created your MainActivity using Xamarin it will automatically generate activity entries in AndroidManifest.xml when you build your app. And the package wiil be actually something like md5XXXXXXXXXXXXXXXX.MainActivity. You should not place your activity in AndroidManifest.xml manually and definetely should not use Xamarin generated md5... packages anywhere. 
If you want to add some intent filters to your activity or other components you should use Xamarin annotations like:
    [IntentFilter (new string[]{"com.pushwoosh.test.xamarin.app.MESSAGE"}, Categories = new string[]{"android.intent.category.DEFAULT"})]

See https://developer.xamarin.com/guides/android/advanced_topics/working_with_androidmanifest.xml/ for more information.
