### ISSUE TITLE
problems trying to compile version play service

### ISSUE THREAD

**Issue by iccunha** [Pushwoosh/pushwoosh-xamarin#5]
`Unhandled Exception:
Java.Lang.UnsupportedOperationException: Google Play Services framework is missing or out of date`

What do I do ?

**Comment by DimanAM** [comment]
It seems you do not have Google Play Sevcices installed on your device or emulator.

https://developers.google.com/android/guides/setup

To test your app when using the Google Play services SDK, you must use either:
- A compatible Android device that runs Android 2.3 or higher and includes Google Play Store.
- The Android emulator with an AVD that runs the Google APIs platform based on Android 4.2.2 or higher.

**Comment by pashko00710** [comment]
Thanks for the quick response! 
We will pass!
