### ISSUE TITLE
Unable to set custom language registering device

### ISSUE THREAD

**Issue by gijsstegehuis** [Pushwoosh/pushwoosh-xamarin#7]
When registering a device through this SDK we are unable to set a custom language. Though this is possible in the remote API registerDevice call, it's not implemented in the SDK. In this specific case we want the user to receive their messages in the app's language, not the device language.

**Comment by wfhm** [comment]
Hi,

You can still create a Tag called "App's language" and set its value for every device based on an app's language; then you will be able to send notifications with different content for different languages.

**Comment by gijsstegehuis** [comment]
I guess you can, but in that way the message body wouldn't be translated in the correct language.

**Comment by viridanti** [comment]
This functionality will be added in one of the future versions of the module.

**Comment by wfhm** [comment]
The functionality is added with the latest release.
