### ISSUE TITLE
Component not yet in store

### ISSUE THREAD

**Issue by sdebruyn** [Pushwoosh/pushwoosh-xamarin#8]
I can't find the component in the Xamarin Component Store, is it possible that the component hasn't been released yet?

**Comment by wfhm** [comment]
Hi,

Currently the compomenet is being distributed via GitHub, so we are not planning to add it to Xamarin Component Store in the nearest future.

**Comment by DimanAM** [comment]
Pushwoosh SDKs can now be added using nuget.
https://www.nuget.org/packages/Pushwoosh.Xamarin.Droid/
https://www.nuget.org/packages/Pushwoosh.Xamarin.iOS/
